name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  # Job 1: Code Quality & Linting
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint JavaScript/TypeScript
      run: npm run lint
      
    - name: Check Prettier formatting
      run: npm run format:check
      
    - name: TypeScript type checking
      run: npm run type-check || true  # Continue on type errors for now

  # Job 2: Test Suite
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install Node dependencies
      run: npm ci
      
    - name: Install Python dependencies
      run: |
        cd packages/backend
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run JavaScript/TypeScript tests
      run: npm run test
      
    - name: Run Python tests
      run: |
        cd packages/backend
        python -m pytest tests/ -v --cov=src --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./packages/backend/coverage.xml
        flags: backend
        name: backend-coverage

  # Job 3: Build All Packages
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build shared package
      run: npm run build --workspace=@engineering-app/shared
      
    - name: Build frontend
      run: npm run build --workspace=@engineering-app/frontend
      
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: packages/frontend/dist/
        retention-days: 7

  # Job 4: Build Desktop Apps (Multiple OS)
  build-desktop:
    name: Build Desktop App
    needs: build
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build shared package
      run: npm run build --workspace=@engineering-app/shared
      
    - name: Build desktop app
      run: npm run build --workspace=@engineering-app/desktop
      
    - name: Build distributables (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run dist:win --workspace=@engineering-app/desktop
      
    - name: Build distributables (macOS)
      if: matrix.os == 'macos-latest'
      run: npm run dist:mac --workspace=@engineering-app/desktop
      
    - name: Build distributables (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm run dist:linux --workspace=@engineering-app/desktop
      
    - name: Upload desktop artifacts
      uses: actions/upload-artifact@v3
      with:
        name: desktop-${{ matrix.os }}
        path: packages/desktop/release/
        retention-days: 30

  # Job 5: Deploy to Staging (on develop branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, build-desktop]
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Download frontend artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: ./dist
        
    - name: Deploy to GitHub Pages (Staging)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: staging

  # Job 6: Deploy to Production (on main branch)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, build-desktop]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download frontend artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: ./dist
        
    - name: Deploy to GitHub Pages (Production)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

  # Job 7: Create Release (on main branch with tags)
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, build-desktop]
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          desktop-windows-latest/**/*
          desktop-macos-latest/**/*
          desktop-ubuntu-latest/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, build]  # Wait for tests to pass
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
        labels: |
          org.opencontainers.image.title=Engineering App Backend
          org.opencontainers.image.description=FastAPI backend for Engineering Application
          org.opencontainers.image.vendor=${{ github.repository_owner }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: packages/backend
        file: packages/backend/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        
    - name: Test Docker image
      run: |
        # Pull the image we just built
        docker pull ghcr.io/${{ github.repository }}/backend:latest
        
        # Run container in background
        docker run -d --name test-container -p 8000:8000 \
          -e DEBUG=true \
          ghcr.io/${{ github.repository }}/backend:latest
        
        # Wait for container to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8000/health
        
        # Clean up
        docker stop test-container
        docker rm test-container
        
    - name: Image vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository }}/backend:latest
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
