name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  update-deps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Update npm dependencies
      run: |
        npx npm-check-updates -u
        npm install

    - name: Update Python dependencies
      run: |
        pip install pip-upgrader
        cd packages/backend
        pip-upgrader requirements.txt --yes

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Weekly Dependency Updates'
        body: |
          Automatic weekly dependency updates
          - Node.js dependencies updated
          - Python dependencies updated
        branch: weekly-dependency-updates
        base: develop
