name: Generate package-lock.json

on:
  push:
    branches: [ main ]
    paths: [ 'package.json' ]
  workflow_dispatch:

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      
    - name: Generate package-lock.json
      run: |
        rm -f package-lock.json
        npm install --workspaces
        
    - name: Commit package-lock.json
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add package-lock.json
        git commit -m "Auto-generate package-lock.json [skip ci]" || echo "No changes to commit"
        git push
